### ISSUE TITLE
Conflicting colors

### ISSUE THREAD

**Issue by ashincoder** [NvChad/site#2]
![2021-08-19-095419_196x87_scrot](https://user-images.githubusercontent.com/83629316/130007488-a1a1e43b-db43-4e9b-9e40-3b6000140752.png)
Try to make the heading look bright in dark mode

**Comment by siduck76** [comment]
> ![2021-08-19-095419_196x87_scrot](https://user-images.githubusercontent.com/83629316/130007488-a1a1e43b-db43-4e9b-9e40-3b6000140752.png)
> Try to make the heading look bright in dark mode

yes someone is working on the dark mode.
